spring:
  application:
    name: eshop-cart-service
  redis:
    host: 192.168.18.134
    port: 30001
    #password:
server:
  port: 8035
  context-path: /
  tomcat:
    uri-encoding: UTF-8

logging:
  config: classpath:log4j2.xml
