spring:
  application:
    name: eshop-web
  redis:
    host: 192.168.18.134
    port: 30001
    #password:
server:
  port: 8033
  context-path: /
  tomcat:
    uri-encoding: UTF-8
myapp:
   restserviceurl:
     account: http://localhost:8034
     cart: http://localhost:8035
     product: http://localhost:8036
   
logging:
  config: classpath:log4j2.xml
