apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eshop-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eshop-redis
    spec:
      containers:
      - name: redis
        image: docker.io/redis:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-redis-ser
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: eshop-redis
  ports:
  - port: 6379 
    nodePort: 30001
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eshop-mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eshop-mysql
    spec:
      containers:
      - name: mysql
        image: docker.io/mysql:5.7
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "HPE_APP"
        - name: MYSQL_USER
          value: "lession"
        - name: MYSQL_PASSWORD
          value: "mypass"
        ports:
          - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-mysql-ser
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: eshop-mysql
  ports:
  - port: 3306
    nodePort: 30002
