apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eshop-product
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eshop-product
    spec:
      containers:
      - name: eshop-product
        image: chen/java:8
        imagePullPolicy:
        ports:
          - containerPort: 8036
        volumeMounts:
        - mountPath: /jar
          name: jarvolume
        command: ["/jar/eshop-product-svc-run.sh"]
      volumes:
      - name: jarvolume
        hostPath:
          path: /root/eShop/eshop_jar
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-product-svc
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: eshop-product
  ports:
  - port: 8036
    targetPort: 8036
