apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eshop-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eshop-web
    spec:
      containers:
      - name: eshop-web
        image: eshop/eshop-web:1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: /opt/app/eshop/web/config
        ports:
          - containerPort: 8033
        command: ["/opt/app/eshop/web/eshop-web-svc-run.sh"]
      volumes:
      - name: config
        configMap:
          name: eshop-web-config  
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-web-svc
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: eshop-web
  ports:
  - port: 8033
    nodePort: 30003
